### ISSUE TITLE
Support for npm, bower, gulp as build steps

### ISSUE THREAD

**Issue by jeremydw** [grow/webreview-commitbot#2]
Beautiful. :) OK, many Grow sites generate HTML with Grow, but generate CSS and JS via Gulp, and manage frontend dependencies with npm and bower. I'm not sure if it makes sense to add these to the grow baseimage, but I'd like them to be available inside the build environment on webreview – and executed alongside the `grow build` command.

Here's the request: get `npm install` working in a pod's work directory, and permit execution of `bower install` and `gulp build` inside the work directory as well – prior to `grow build`.

**Comment by fotinakis** [comment]
@jeremydw 

Ok! After thinking through the architecture, I added support for this to the grow docker baseimage — you can now run any one-off commands with all the correct grow dependencies present:

``` bash
docker run --rm=true --workdir=/tmp -i grow/baseimage \
  bash -c "git clone https://github.com/grow/growsdk.org.git && grow build growsdk.org/"
```

https://github.com/grow/baseimage-grow
https://hub.docker.com/r/grow/baseimage/

This will provide isolated, versioned builds of grow sites with preprocessor support, and an easy upgrade path between grow versions (just `docker pull grow/baseimage`). However, it's not going to work on Managed VMs, but I've thought of some ways we can architect buildbot for that.

Can you push 0.0.53 to pip when you get a chance? I've had to workaround a few things until that's up.
